apiVersion: apps/v1
kind: Deployment
metadata:
  name: cronaseat
  labels:
    app: cronaseat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cronaseat
  template:
    metadata:
      labels:
        app: cronaseat
    spec:
      containers:
        - name: cronaseat
          image: username/cronaseat:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5